import { getAllPackages } from "@/lib/data/packages";
import { getAllQuotationsAdmin } from "@/lib/data/quotations";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Badge } from "@/components/ui/badge";

export default async function AdminDashboard() {
  const packages = await getAllPackages();
  const quotations = await getAllQuotationsAdmin();

  return (
    <div className="space-y-8">
      {/* Packages Section */}
      <div className="bg-white dark:bg-gray-800 p-8 rounded-lg shadow-sm border border-gray-100 dark:border-gray-700">
        <h2 className="text-2xl font-bold mb-4">Packages Inventory</h2>
        <p className="text-gray-600 dark:text-gray-300 mb-6">
          Overview of all available travel packages across destinations.
        </p>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Title</TableHead>
              <TableHead>Destination</TableHead>
              <TableHead>Nights</TableHead>
              <TableHead className="text-right">Supplier Cost</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {packages.map((pkg: any) => (
              <TableRow key={pkg.id}>
                <TableCell className="font-medium">{pkg.title}</TableCell>
                <TableCell>{pkg.destination}</TableCell>
                <TableCell>{pkg.nights}</TableCell>
                <TableCell className="text-right">${pkg.baseSupplierCost.toFixed(2)}</TableCell>
              </TableRow>
            ))}
            {packages.length === 0 && (
              <TableRow>
                <TableCell colSpan={4} className="text-center py-6 text-muted-foreground">
                  No packages found.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </div>

      {/* Quotations Section */}
      <div className="bg-white dark:bg-gray-800 p-8 rounded-lg shadow-sm border border-gray-100 dark:border-gray-700">
        <h2 className="text-2xl font-bold mb-4">All Agent Quotations</h2>
        <p className="text-gray-600 dark:text-gray-300 mb-6">
          A bird's-eye view of all quotations generated by agents.
        </p>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>ID</TableHead>
              <TableHead>Agent</TableHead>
              <TableHead>Customer</TableHead>
              <TableHead>Items</TableHead>
              <TableHead>Status</TableHead>
              <TableHead className="text-right">Total</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {quotations.map((quote: any) => (
              <TableRow key={quote.id}>
                <TableCell className="font-mono text-xs">{quote.id.slice(-6).toUpperCase()}</TableCell>
                <TableCell>{quote.agent?.name || "Unknown Agent"}</TableCell>
                <TableCell>{quote.customerName}</TableCell>
                <TableCell>{quote._count.items}</TableCell>
                <TableCell>
                  <Badge variant={quote.status === 'CONFIRMED' ? 'default' : 'secondary'}>
                    {quote.status}
                  </Badge>
                </TableCell>
                <TableCell className="text-right font-medium">${quote.totalAmount.toFixed(2)}</TableCell>
              </TableRow>
            ))}
            {quotations.length === 0 && (
              <TableRow>
                <TableCell colSpan={6} className="text-center py-6 text-muted-foreground">
                  No quotations found.
                </TableCell>
              </TableRow>
            )}
          </TableBody>
        </Table>
      </div>
    </div>
  );
}
